options:
  # merge-default-rules: false
  # formatter: html

files:
#  include: 'source/stylesheets/**/*.s+(a|c)ss'
#  ignore:
#    - 'source/stylesheets/foundations/**/*.*'

rules:
  hex-length: 0
  no-color-literals: 0
  property-sort-order: 0
#  extends-before-mixins: 2
#  extends-before-declarations: 2
